### ISSUE TITLE
problem when submitting raffle

### ISSUE THREAD

**Issue by HugoSecteur4** [NgoPCuong/SJSocialismRaffle#1]
every time when submitting raffle, this message appears : 

Consumer Thread is Submitting Raffle...
{"data":null,"errors":[{"message":"Request not verified","locations":[{"line":2,"column":3}],"path":["requestOrder"]}]}

need help please

**Comment by NgoKyle** [comment]
What's your settings on configure file?

**Comment by HugoSecteur4** [comment]
twocaptchaKey=MY API KEY

url=https://slamjamsocialism-drops.com/drops/140

sitekey=6LfYhz0UAAAAAJFKp28Sg0NnAEIPMfKI1RJSGsdB

productNo=115

raffleNo=140

phoneAreaCode=033

catchAllDomain=amaizing.us

catchAllPrefix=shoes

producerThread=50

consumerThread=8

**Comment by HugoSecteur4** [comment]
And amaizing.us is my domain on namecheap

**Comment by NgoKyle** [comment]
This script only works for US for now. Are u in US?

**Comment by NgoKyle** [comment]
Hmm not sure what casuing that error, never seen before

**Comment by HugoSecteur4** [comment]
I'm not in the US, I'm in France

**Comment by NgoKyle** [comment]
This script was written for US only.
