### ISSUE TITLE
How do you install libraries from requirements.txt?

### ISSUE THREAD

**Issue by hasheemthatbeet** [NgoPCuong/SJSocialismRaffle#2]
it might be a lot, but a video tutorial of the process would be appreciated!

**Comment by NgoKyle** [comment]
install pip first. then run 'pip3 install -r requirements.txt'

**Comment by hasheemthatbeet** [comment]
Thanks bro! Do you think its too late to do it now? And will this work for
future releases?

**Comment by NgoKyle** [comment]
Yes this works for future releases. All you need to do is change the config.

**Comment by delorett** [comment]
Hi man, i saw your script yesterday late in the evening but i saw it works
online, i have a cookgroup and i ll appreciate if you ll be able to give us
your script for each release and for the possoble shops. of course i ll pay
for your work and if you want we can talk about it. Thanks
Enrico Delorenzi

Il venerdì 3 agosto 2018, NgoPCuong <notifications@github.com> ha scritto:
